In [17]:
import numpy as np


In [18]:
# NumPy arrays are homogeneous (mixing types --> upcasting to same compatible type)
print(np.zeros(10, dtype=int)) # specify shape (or len if 1D), data type
print(np.ones(20, dtype=float))

[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
np.full((3, 3), "!") # more general version

array([['!', '!', '!'],
       ['!', '!', '!'],
       ['!', '!', '!']], dtype='<U1')

In [20]:
# Range & Random
print(np.arange(0, 20, 2))
print(np.linspace(0, 1, 10))

[ 0  2  4  6  8 10 12 14 16 18]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [21]:
np.random.random((3, 3)) # specify size

array([[0.75244933, 0.98667704, 0.51064483],
       [0.26918642, 0.6912318 , 0.91567615],
       [0.52175853, 0.02475993, 0.79910247]])

In [22]:
np.random.randint(0, 10, (3, 3))

array([[8, 9, 8],
       [5, 4, 7],
       [0, 7, 5]])