In [16]:
import numpy as np

# Attributes of Arrays (Accessing Information About Arrays)

In [17]:
np.random.seed(0)

# Note: the length of the tuple determines the dimensions of the array; e.g., (1, 6) would be a 2D array of a single row of 6
a = np.random.randint(low=0, high=10, size=6) # 1D array
b = np.random.randint(low=0, high=10, size=(3, 4)) # 2D array
c = np.random.randint(low=0, high=10, size=(3, 4, 5)) # 3D array

d = np.array([1, 2, 3, 4]) # np.array is used to convert Python arrays to NumPy arrays

print(a)
print()
print(b)
print()
print(c)
print()
print(d)

[5 0 3 3 7 9]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]

[1 2 3 4]


In [18]:
# Information regarding array
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

3
(3, 4, 5)
60
int64


In [19]:
# Information regarding items
print(c.itemsize)
print(c.nbytes) # itemsize * size

8
480


# Accessing Array Values

In [20]:
# Array Indexing
print(c[1, 1, 1]) # multiple indexing can be separated with commas

7


In [21]:
# Modifying Elements in Array
print(c[1, 1])
print()

c[1,1] = 1 # When modifying elements and provided value is not suitable, NumPy broadcasts value to the entire "slice"
print(c)

# If assigning an incomptatible type (e.g., expected a 1D array, but given 2D array, error will occur)

[4 7 3 2 7]

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [1 1 1 1 1]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [22]:
# Accessing Rows and Columns
print(c[0, 0, :]) # Access all columns of first row of first block
print(c[1, :, 0]) # Access first column of second block

print(c[:, 0, :]) # 2D array of the first row of each block

[8 1 5 9 8]
[0 1 2 5]
[[8 1 5 9 8]
 [0 1 9 9 0]
 [4 9 8 1 1]]


### Note: Slices of numpy arrays return views, not copies

In [23]:
# To work with copies, use the .copy() method
print(b)
print()

# Example of modifying view
row1 = b[0]
print(row1)
row1[0] = 0
print(row1)
print()

# Example of modifying copy
row2 = b[1]
print(row2)
example = b[1].copy()
example[0] = 0
print(example)
print(row2) # unchanged

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

[3 5 2 4]
[0 5 2 4]

[7 6 8 8]
[0 6 8 8]
[7 6 8 8]


# Transforming Arrays: Reshaping, Concatenation, and Splitting

In [24]:
# Reshaping Arrays (must be same size, returns NEW array)
# Example: Reshaping to a higher dimension
a = np.zeros(shape=9, dtype=int)
print(a)
print(a.reshape((3, 3)))
print()

# Example: Reshaping to a lower dimension
b = np.ones(shape=(2, 3), dtype=float)
print(b)
print(b.reshape(1, 6))

[0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]]


In [25]:
# Concatenating Arrays (returns NEW array)
# Example: Same 1-D dimension concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b])) # accepts list of arrays

# Example: Multi-Dimension Arrays
c = np.array([
    [1, 2, 3,],
    [4, 5, 6]
])
print(np.concatenate([c, c])) # by default, concatenation is along the first axis (zero-indexed); for 2D arrays, this means rows

print(np.concatenate([c, c], axis=1)) # the next "smaller" axis can be specified

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### Squeezing Arrays (np.squeeze)

In [26]:
# np.squeeze removes single-dimensional entries from the shape of an array.
a = np.array([[[0], [1], [2]]])
print("Original array a:")
print(a)
print("Shape of a:", a.shape)

b = np.squeeze(a)
print("Squeezed array b:")
print(b)
print("Shape of b:", b.shape)

# You can also specify which axes to squeeze
c = np.array([[[0, 1], [2, 3]]])
print("Original array c:")
print(c)
print("Shape of c:", c.shape)

# Squeeze only the first axis (axis 0)
d = np.squeeze(c, axis=0)
print("Squeezed array d (axis 0):")
print(d)
print("Shape of d:", d.shape)

# Squeeze only the last axis (axis 2)
# This will raise an error if axis 2 is not a single dimension
try:
    e = np.squeeze(c, axis=2)
except ValueError as e_val:
    print(f"\nError squeezing axis 2 of c: {e_val}")

# Example where squeezing multiple axes is possible
f = np.zeros((1, 2, 1, 3, 1))
print("Original array f:")
print(f)
print("Shape of f:", f.shape)

g = np.squeeze(f)
print("Squeezed array g:")
print(g)
print("Shape of g:", g.shape)

Original array a:
[[[0]
  [1]
  [2]]]
Shape of a: (1, 3, 1)
Squeezed array b:
[0 1 2]
Shape of b: (3,)
Original array c:
[[[0 1]
  [2 3]]]
Shape of c: (1, 2, 2)
Squeezed array d (axis 0):
[[0 1]
 [2 3]]
Shape of d: (2, 2)

Error squeezing axis 2 of c: cannot select an axis to squeeze out which has size not equal to one
Original array f:
[[[[[0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]]]]]
Shape of f: (1, 2, 1, 3, 1)
Squeezed array g:
[[0. 0. 0.]
 [0. 0. 0.]]
Shape of g: (2, 3)


In [27]:
# Shortcuts for Concatenate: vstack(), hstack(), and dstack()
d = np.random.randint(0, 100, size=(3, 3, 3))
print("Original Array:")
print(d)
print("-------------------\n")

# vstack() always concatenates along 1st axis (equivalent to concatencate([...], axis=0)
print(np.vstack([d, d])) # increases depth (number of plane slices) for 3D array
print("-------------------\n")

# hstack() always concatenates along 2nd axis
print(np.hstack([d, d])) # increases height (number of rows) for 3D array
print("-------------------\n")

# dstack() always concatenates along 3rd axis
print(np.dstack([d, d])) # increases width (number of cols) for a 3D array

Original Array:
[[[47  3 76]
  [52 78 15]
  [20 99 58]]

 [[23 79 13]
  [85 48 49]
  [69 41 35]]

 [[64 95 69]
  [94  0 50]
  [36 34 48]]]
-------------------

[[[47  3 76]
  [52 78 15]
  [20 99 58]]

 [[23 79 13]
  [85 48 49]
  [69 41 35]]

 [[64 95 69]
  [94  0 50]
  [36 34 48]]

 [[47  3 76]
  [52 78 15]
  [20 99 58]]

 [[23 79 13]
  [85 48 49]
  [69 41 35]]

 [[64 95 69]
  [94  0 50]
  [36 34 48]]]
-------------------

[[[47  3 76]
  [52 78 15]
  [20 99 58]
  [47  3 76]
  [52 78 15]
  [20 99 58]]

 [[23 79 13]
  [85 48 49]
  [69 41 35]
  [23 79 13]
  [85 48 49]
  [69 41 35]]

 [[64 95 69]
  [94  0 50]
  [36 34 48]
  [64 95 69]
  [94  0 50]
  [36 34 48]]]
-------------------

[[[47  3 76 47  3 76]
  [52 78 15 52 78 15]
  [20 99 58 20 99 58]]

 [[23 79 13 23 79 13]
  [85 48 49 85 48 49]
  [69 41 35 69 41 35]]

 [[64 95 69 64 95 69]
  [94  0 50 94  0 50]
  [36 34 48 36 34 48]]]


In [28]:
# Splitting Arrays (KEEPS DIMENSIONALITY; e.g., 3x3x3 split into 3 planes would become 3 of 1x3x3)
d = np.random.randint(0, 100, size=(3, 3, 3))
print("Original Array:")
print(d)
print("-------------------\n")

# Example: Splitting by section number (If not divisible by provided section number, an error will occur)
print(np.split(d, 3, axis=0)) # note: the "array" text printed is only due to __repr__; functions just like a list of subarrays
print("-------------------\n")

# Example: Splitting by index list
print(np.split(d, [1, 2], axis=0)) # same effect, noting that these dividers work exclusively ([:1], [1:2], [2:])


Original Array:
[[[93  3 98]
  [42 77 21]
  [73  0 10]]

 [[43 58 23]
  [59  2 98]
  [62 35 94]]

 [[67 82 46]
  [99 20 81]
  [50 27 14]]]
-------------------

[array([[[93,  3, 98],
        [42, 77, 21],
        [73,  0, 10]]]), array([[[43, 58, 23],
        [59,  2, 98],
        [62, 35, 94]]]), array([[[67, 82, 46],
        [99, 20, 81],
        [50, 27, 14]]])]
-------------------

[array([[[93,  3, 98],
        [42, 77, 21],
        [73,  0, 10]]]), array([[[43, 58, 23],
        [59,  2, 98],
        [62, 35, 94]]]), array([[[67, 82, 46],
        [99, 20, 81],
        [50, 27, 14]]])]


In [29]:
# Shortcuts for Splitting Arrays Along 1st/2nd/3rd Axes: vsplit(), hsplit(), dsplit()
print(np.vsplit(d, 3)) # along axis=0 --> into individual planes --> 3 of (1, 3, 3) / depth=1, height=3, width=3

print(np.hsplit(d, 3)) # along axis=1 --> into horizontal sliced planes (split by rows) --> 3 of (3, 1, 3) / depth=3, height=1, width=3

print(np.dsplit(d, 3)) # along axis=2 --> into vertically sliced planes (split by cols) --> 3 of (3, 3, 1) / depth=3, height=3, width=1

[array([[[93,  3, 98],
        [42, 77, 21],
        [73,  0, 10]]]), array([[[43, 58, 23],
        [59,  2, 98],
        [62, 35, 94]]]), array([[[67, 82, 46],
        [99, 20, 81],
        [50, 27, 14]]])]
[array([[[93,  3, 98]],

       [[43, 58, 23]],

       [[67, 82, 46]]]), array([[[42, 77, 21]],

       [[59,  2, 98]],

       [[99, 20, 81]]]), array([[[73,  0, 10]],

       [[62, 35, 94]],

       [[50, 27, 14]]])]
[array([[[93],
        [42],
        [73]],

       [[43],
        [59],
        [62]],

       [[67],
        [99],
        [50]]]), array([[[ 3],
        [77],
        [ 0]],

       [[58],
        [ 2],
        [35]],

       [[82],
        [20],
        [27]]]), array([[[98],
        [21],
        [10]],

       [[23],
        [98],
        [94]],

       [[46],
        [81],
        [14]]])]


### Finding Max/Min Values and Their Indices (np.argmax, np.argmin)

In [30]:
# Create a sample array
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original Array:")
print(arr)

# np.argmax: Returns the indices of the maximum values along an axis.
# If axis is not specified, the array is flattened.
print("Index of maximum value in flattened array (np.argmax(arr)):", np.argmax(arr))

# np.argmax along axis 0 (columns)
print("Index of maximum values along axis 0 (np.argmax(arr, axis=0)):", np.argmax(arr, axis=0))

# np.argmax along axis 1 (rows)
print("Index of maximum values along axis 1 (np.argmax(arr, axis=1)):", np.argmax(arr, axis=1))

# np.argmin: Returns the indices of the minimum values along an axis.
# If axis is not specified, the array is flattened.
print("Index of minimum value in flattened array (np.argmin(arr)):", np.argmin(arr))

# np.argmin along axis 0 (columns)
print("Index of minimum values along axis 0 (np.argmin(arr, axis=0)):", np.argmin(arr, axis=0))

# np.argmin along axis 1 (rows)
print("Index of minimum values along axis 1 (np.argmin(arr, axis=1)):", np.argmin(arr, axis=1))

# Getting the actual max/min values
print("Maximum value in array (np.max(arr)):", np.max(arr))
print("Minimum value in array (np.min(arr)):", np.min(arr))

print("Maximum values along axis 0 (np.max(arr, axis=0)):", np.max(arr, axis=0))
print("Minimum values along axis 0 (np.min(arr, axis=0)):", np.min(arr, axis=0))

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Index of maximum value in flattened array (np.argmax(arr)): 8
Index of maximum values along axis 0 (np.argmax(arr, axis=0)): [2 2 2]
Index of maximum values along axis 1 (np.argmax(arr, axis=1)): [2 2 2]
Index of minimum value in flattened array (np.argmin(arr)): 0
Index of minimum values along axis 0 (np.argmin(arr, axis=0)): [0 0 0]
Index of minimum values along axis 1 (np.argmin(arr, axis=1)): [0 0 0]
Maximum value in array (np.max(arr)): 90
Minimum value in array (np.min(arr)): 10
Maximum values along axis 0 (np.max(arr, axis=0)): [70 80 90]
Minimum values along axis 0 (np.min(arr, axis=0)): [10 20 30]
