In [10]:
import numpy as np

# Universal Functions in NumPy

In [11]:
# Arithmetic Operators in NumPy (Universal Functions)
# Note how all operations are done element-wise
# Operations are done across the axis in a manner that collapses the axis (removes it from resulting array)
a = np.arange(4)
print(a)
print("---------")

# Addition
print(a + 5)
print("---------")

# Subtraction
print(a - 1)
print("---------")

# Multiplication
print(a * 3)
print("---------")

# Division
print(a / 2)
print("---------")

# Floor Division
print(a // 2)
print("---------")

# Exponentiation
print(a ** 2)
print("---------")

# Modulus
print(a % 2)
print("---------")

[0 1 2 3]
---------
[5 6 7 8]
---------
[-1  0  1  2]
---------
[0 3 6 9]
---------
[0.  0.5 1.  1.5]
---------
[0 0 1 1]
---------
[0 1 4 9]
---------
[0 1 0 1]
---------


# Absolute Value

In [12]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

[2 1 0 1 2]


# Trigonometric Functions

In [13]:
theta = np.linspace(0, np.pi, 3)
print(f'theta      = {theta}')
print(f'sin(theta) = {np.sin(theta)}')
print(f'cos(theta) = {np.cos(theta)}')
print(f'tan(theta) = {np.tan(theta)}')

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# Exponential and Logarithmic Functions

In [14]:
x = [1, 2, 3]
print("x      =", x)
print("e^x    =", np.exp(x))
print("2^x    =", np.exp2(x))
# Note: Operations are done element-wise
print("3^x    =", np.power(3, x)) # first argument is base; second is exponent; either can be array (but must be broadcastable)


x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x      = [1, 2, 3]
e^x    = [ 2.71828183  7.3890561  20.08553692]
2^x    = [2. 4. 8.]
3^x    = [ 3  9 27]
x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


# Aggregation Functions

NumPy provides a variety of aggregation functions that allow you to perform calculations on entire arrays or specific axes of an array. These functions are highly optimized and efficient for numerical computations.

### Common Aggregation Functions

- `np.sum()`: Computes the sum of all elements in an array.
- `np.min()`: Finds the minimum value in an array.
- `np.max()`: Finds the maximum value in an array.
- `np.mean()`: Calculates the arithmetic mean of the elements.
- `np.std()`: Computes the standard deviation.
- `np.var()`: Calculates the variance.

These functions can be applied to the entire array or along a specified axis. For a 2D array, `axis=0` refers to the columns, and `axis=1` refers to the rows.

In [15]:
# Example of Aggregation Functions
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Sum of all elements
print(f'Sum of all elements: {np.sum(matrix)}')

# Minimum value
print(f'Minimum value: {np.min(matrix)}')

# Maximum value
print(f'Maximum value: {np.max(matrix)}')

# Mean of all elements
print(f'Mean of all elements: {np.mean(matrix)}')

# Sum of each column (axis=0)
print(f'Sum of each column: {np.sum(matrix, axis=0)}')

# Sum of each row (axis=1)
print(f'Sum of each row: {np.sum(matrix, axis=1)}')

Sum of all elements: 45
Minimum value: 1
Maximum value: 9
Mean of all elements: 5.0
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]


# Broadcasting Rules

Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. In short, if a smaller array's shape can be expanded to match a larger array's shape, then the operation is performed element-wise. This avoids the need to create explicit copies of the smaller array to match the larger one, which can be very memory-efficient.

### Broadcasting Rules

1. **Rule 1:** If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
2. **Rule 2:** If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. **Rule 3:** If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [16]:
# Broadcasting Example 1: Array and a Scalar
a = np.array([1, 2, 3])
b = 2
print(f'Array a: {a}')
print(f'Scalar b: {b}')
print(f'a * b: {a * b}')

# Broadcasting Example 2: 1D and 2D arrays
M = np.ones((3, 3))
print(f'Matrix M: {M}')
print(f'a + M: {a + M}')

Array a: [1 2 3]
Scalar b: 2
a * b: [2 4 6]
Matrix M: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
a + M: [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
