# Sorting Arrays
Sorting is a fundamental operation in data analysis. NumPy provides efficient functions for sorting arrays, which are often more performant than Python's built-in `sort` and `sorted` functions. This notebook covers the basics of sorting in NumPy, including fast sorting, partial sorts, and a practical example with k-nearest neighbors.

## Fast Sorting in NumPy: `np.sort`

For sorting NumPy arrays, the `np.sort` function is the recommended approach. It is optimized for NumPy arrays and typically uses a quicksort algorithm. You can also specify other algorithms like mergesort and heapsort.
The `np.sort` function returns a sorted copy of the array, leaving the original array unchanged. To sort an array in-place, you can use the `sort` method of the array object itself.

In [1]:
import numpy as np

x = np.array([2, 1, 4, 3, 5])
print("Original array:", x)

sorted_x = np.sort(x)
print("Sorted array (copy):", sorted_x)

x.sort()
print("Array sorted in-place:", x)

Original array: [2 1 4 3 5]
Sorted array (copy): [1 2 3 4 5]
Array sorted in-place: [1 2 3 4 5]


### Sorting Multi-dimensional Arrays

`np.sort` can also be used to sort multi-dimensional arrays along a specified axis. You can sort each row or each column independently.

In [2]:
# Note: sorting is done **across** each axis
# By default, if axis is unspecified, goes to last axis, which is across cols (in other words, rows are sorted)

y = np.array([[3, 2, 1], [6, 5, 4]])
print("Original array:\n", y)

# Sort along columns (down each row)
print("Sorted along columns:\n", np.sort(y, axis=0))

# Sort along rows (across each col)
print("Sorted along rows:\n", np.sort(y, axis=1))

Original array:
 [[3 2 1]
 [6 5 4]]
Sorted along columns:
 [[3 2 1]
 [6 5 4]]
Sorted along rows:
 [[1 2 3]
 [4 5 6]]


## Partial Sorts: Partitioning

In some cases, you may not need to sort the entire array. Instead, you might only need to find the k-smallest items. NumPy's `np.partition` function is more efficient for this purpose. It partitions the array such that the k-th element is in its sorted position, and all smaller elements are to its left, while all larger elements are to its right.

In [3]:
z = np.array([7, 2, 3, 1, 6, 5, 4])
print("Original array:", z)

# Find the 3 smallest items
print("Partitioned array (k=3):", np.partition(z, 3))

Original array: [7 2 3 1 6 5 4]
Partitioned array (k=3): [2 1 3 4 6 5 7]


### Partitioning Multi-dimensional Arrays

In [4]:
# With np.partition, we can find the k smallest items in each row/col
y = np.array([[3, 2, 1], [6, 5, 4]])
print("Original array:\
", y)

# Partition each row to get the 2 smallest elements
print("Partitioned array (k=2, axis=1):\
", np.partition(y, 2, axis=1))

Original array: [[3 2 1]
 [6 5 4]]
Partitioned array (k=2, axis=1): [[1 2 3]
 [4 5 6]]


 **`argsort` and `argpartition`**

In many cases, you don't need the sorted values themselves, but rather the *indices* of the sorted values. NumPy provides `argsort` and `argpartition` for this purpose. These functions are particularly useful when you need to sort one array based on the values in another array.

`argsort`

The `np.argsort` function returns the indices that would sort an array.

In [5]:
x = np.array([2, 1, 4, 3, 5])
print("Original array:", x)

# Get the indices that would sort the array
i = np.argsort(x)
print("Indices of sorted array:", i)

# Use the indices to access the sorted elements
print("Sorted array:", x[i])

Original array: [2 1 4 3 5]
Indices of sorted array: [1 0 3 2 4]
Sorted array: [1 2 3 4 5]


`argpartition`

Similarly, `np.argpartition` returns the indices that would partition an array. This is useful for finding the indices of the k-smallest values without sorting the entire array.

In [6]:
z = np.array([7, 2, 3, 1, 6, 5, 4])
print("Original array:", z)

# Get the indices of the 3 smallest items
k = 3
i = np.argpartition(z, k)
print("Indices of partitioned array (k=3):", i)

# The first k indices give the k smallest values
print("The {} smallest values are:".format(k), z[i[:k]])

Original array: [7 2 3 1 6 5 4]
Indices of partitioned array (k=3): [1 3 2 6 4 5 0]
The 3 smallest values are: [2 1 3]


## Example: k-Nearest Neighbors

Sorting is a key component of the k-Nearest Neighbors (KNN) algorithm. KNN classifies a new data point based on the majority class of its nearest neighbors. To find these neighbors, we calculate the distance from the new point to all other points and then sort the distances.

In [ ]:
from collections import Counter

# Sample training data
X_train = np.array([[1, 2], [2, 3], [3, 1], [6, 7], [7, 8], [8, 6]])
y_train = ['A', 'A', 'A', 'B', 'B', 'B']

# New point to classify
new_point = [4, 5]

# 1. Calculate distances
distances = [np.linalg.norm(new_point - train_point) for train_point in X_train]
print("Distances:", distances)

# 2. Sort by distance and get indices
k = 3
nearest_neighbor_indices = np.argsort(distances)[:k]
print("Indices of nearest neighbors:", nearest_neighbor_indices)

# 3. Vote for the class
nearest_neighbor_labels = [y_train[i] for i in nearest_neighbor_indices]
predicted_class = Counter(nearest_neighbor_labels).most_common(1)[0][0]
print("Predicted class:", predicted_class)

[-3 -3]
Distances: [np.float64(4.242640687119285), np.float64(2.8284271247461903), np.float64(4.123105625617661), np.float64(2.8284271247461903), np.float64(4.242640687119285), np.float64(4.123105625617661)]
Indices of nearest neighbors: [1 3 2]
Predicted class: A
